import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "ANDRE HVAC International Inc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white">
        <header className="ahi-theme-color">
          <div className="flex flex-col  py-2 px-2 sm:px-5">
            <div className="flex flex-row items-center justify-between">
              <div className="flex flex-row  w-4/5 items-center">
                <Image
                  className="w-[10%] sm:w-1/12"
                  src="/logo.png"
                  width={240}
                  height={240}
                  alt="logo"
                />
                <div className="pl-[1.25%] flex flex-col">
                  <h1 className="text-[3.5vw] sm:text-[3vw]  font-bold">
                    {" "}
                    ANDRE HVAC International Inc.{" "}
                  </h1>
                  <h2 className="text-[1.75vw] sm:text-[1.5vw]  font-bold">
                    VIBRATION CONTROL PRODUCTS
                  </h2>
                </div>
              </div>
              <div className="flex flex-row justify-end items-center">
                <button className="whitespace-nowrap text-center text-[2vw] sm:text-[1.5vw]  px-2 py-1  h-fit rounded-lg border-2 font-bold border-neutral-400  bg-red-600 transition-all  hover:bg-red-600/55">
                  Login
                </button>
                <div className="md:hidden py-0">
                  <Navbar></Navbar>
                </div>
              </div>
            </div>
            <div className="hidden md:block">
              <Navbar></Navbar>
            </div>
          </div>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
