import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Image from 'next/image'



export const metadata: Metadata = {
  title: "ANDRE HVAC International Inc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">   
      <body className="text-white">
      <header className="ahi-theme-color">
        <div className="flex flex-col">
          <div className="mt-5 flex flex-row items-center">
          <Image className="ml-5 w-10 h-10 lmd:w-16 lmd:h-16" src="/logo.png" width={60} height={60} alt="logo"/>
          <div className="pl-5 flex flex-col">
           <h1 className="text-l lmd:text-3xl md:text-5xl font-bold"> ANDRE HVAC International Inc. </h1>
           <h2 className="text-xs lmd:text-xl md:text-2xl font-bold">VIBRATION CONTROL PRODUCTS</h2>
          </div>
          </div>
          <Navbar></Navbar>
        </div>
        </header>
        {children}
      <footer>Footer</footer>
      </body>
      
    </html>
  );
}
